name: project_xenon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  google_fonts: ^6.2.1
  go_router: ^14.6.1
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:


flutter:
  uses-material-design: true
